### ISSUE TITLE
undefined method 'to_i' in Fastlane v2.89.0

### ISSUE THREAD

**Issue by JesseScott** [Jems22/fastlane-plugin-increment_version_code#10]
First off, thanks for your plugin - it's super useful!

Today i updated to Fastlane 2.89.0 and am getting an error trying to pass a specific versionCode into your lane.

**Actions**

```
[08:01:31]: Cruising back to lane 'android publish' 🚘
[08:01:31]: -------------------------------------------------
[08:01:31]: --- Step: Switch to android version_code lane ---
[08:01:31]: -------------------------------------------------
[08:01:31]: Cruising over to lane 'android version_code' 🚖
[08:01:31]: ---------------------------------------------
[08:01:31]: --- Step: google_play_track_version_codes ---
[08:01:31]: ---------------------------------------------
[08:01:33]: No version codes found in track 'internal'
[08:01:33]: ---------------------------------------------
[08:01:33]: --- Step: google_play_track_version_codes ---
[08:01:33]: ---------------------------------------------
[08:01:34]: Found '16' version codes in track 'alpha'
[08:01:34]: ---------------------------------------------
[08:01:34]: --- Step: google_play_track_version_codes ---
[08:01:34]: ---------------------------------------------
[08:01:36]: No version codes found in track 'beta'
[08:01:36]: ---------------------------------------------
[08:01:36]: --- Step: google_play_track_version_codes ---
[08:01:36]: ---------------------------------------------
[08:01:38]: No version codes found in track 'production'
[08:01:38]: 17
[08:01:38]: Cruising back to lane 'android publish' 🚘
[08:01:38]: ------------------------------------
[08:01:38]: --- Step: increment_version_code ---
[08:01:38]: ------------------------------------
[08:01:38]: You passed invalid parameters to 'increment_version_code'.
[08:01:38]: Check out the error below and available options by running `fastlane action increment_version_code`
+-----------------------------+---------------+
|                Lane Context                 |
+-----------------------------+---------------+
| DEFAULT_PLATFORM            | android       |
| PLATFORM_NAME               | android       |
| LANE_NAME                   | android alpha |
| GIT_REPO_WAS_CLEAN_ON_START | true          |
+-----------------------------+---------------+
[08:01:38]: undefined method `to_i' for true:TrueClass
Did you mean?  to_s

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying fastlane version          | 0           |
| 2    | default_platform                    | 0           |
| 3    | import_from_git                     | 1           |
| 4    | ensure_git_status_clean             | 0           |
| 5    | Switch to android publish lane      | 0           |
| 6    | Switch to android clean lane        | 0           |
| 7    | gradle                              | 1           |
| 8    | Switch to android version_code lane | 0           |
| 9    | google_play_track_version_codes     | 1           |
| 10   | google_play_track_version_codes     | 1           |
| 11   | google_play_track_version_codes     | 1           |
| 12   | google_play_track_version_codes     | 1           |
| 💥   | increment_version_code              | 0           |
+------+-------------------------------------+-------------+

```

**Error**

```
[08:01:38]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:236:in `auto_convert_value': [!] undefined method `to_i' for true:TrueClass (NoMethodError)
Did you mean?  to_s
Did you mean?  to_s
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:85:in `block in verify_value_exists'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `each'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `verify_value_exists'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:66:in `initialize'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `new'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `create'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/configuration_helper.rb:8:in `parse'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:242:in `block (2 levels) in execute_action'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from ../../../../../../../../../var/folders/6v/91hsb4cx29v4qjf0g06lt0740000gp/T/fl_clone20180403-34750-18fndfu/fastlane.git/fastlane/Foundation/Android/Fastfile:120:in `block (2 levels) in parsing_binding'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from ../../../../../../../../../var/folders/6v/91hsb4cx29v4qjf0g06lt0740000gp/T/fl_clone20180403-34750-18fndfu/fastlane.git/fastlane/Foundation/Android/Fastfile:251:in `block (2 levels) in parsing_binding'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/bin/fastlane:20:in `<top (required)>'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jessescott/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Fastlane Env**

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import_from_git(
  url: "git@bitbucket.org:eventbase/fastlane.git",
  branch: "feature/add-android-foundation",
  path: "fastlane/Foundation/Android/Fastfile"
)

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
## JSON Key File
json_key_file "play_store/GooglePlayAndroidDeveloper-cb4fd306e9a6.json"

## Package Name
package_name "com.eventbasedev.ebproductapp"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.89.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.1.0        |
| executable-hooks                       | 1.3.2        |
| bundler-unload                         | 1.0.2        |
| rubygems-bundler                       | 1.4.4        |
| bundler                                | 1.16.0       |
| io-console                             | 0.4.6        |
| CFPropertyList                         | 3.0.0        |
| public_suffix                          | 2.0.5        |
| addressable                            | 2.5.2        |
| atomos                                 | 0.1.2        |
| babosa                                 | 1.0.2        |
| claide                                 | 1.0.2        |
| colored                                | 1.2          |
| colored2                               | 3.1.2        |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| unf_ext                                | 0.0.7.5      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20170404 |
| dotenv                                 | 2.2.1        |
| excon                                  | 0.62.0       |
| multipart-post                         | 2.0.0        |
| faraday                                | 0.14.0       |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday_middleware                     | 0.12.2       |
| fastimage                              | 2.1.1        |
| gh_inspector                           | 1.1.3        |
| jwt                                    | 2.1.0        |
| little-plugger                         | 1.1.4        |
| multi_json                             | 1.13.1       |
| logging                                | 2.2.2        |
| memoist                                | 0.16.0       |
| os                                     | 0.9.6        |
| signet                                 | 0.8.1        |
| googleauth                             | 0.6.2        |
| httpclient                             | 2.8.3        |
| mime-types-data                        | 3.2016.0521  |
| mime-types                             | 3.1          |
| uber                                   | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.1        |
| google-api-client                      | 0.13.6       |
| json                                   | 2.1.0        |
| mini_magick                            | 4.5.1        |
| multi_xml                              | 0.6.0        |
| plist                                  | 3.4.0        |
| rubyzip                                | 1.2.1        |
| security                               | 0.1.3        |
| naturally                              | 2.1.0        |
| simctl                                 | 1.6.3        |
| slack-notifier                         | 2.3.2        |
| terminal-notifier                      | 1.8.0        |
| unicode-display_width                  | 1.3.0        |
| terminal-table                         | 1.8.0        |
| tty-screen                             | 0.6.4        |
| tty-cursor                             | 0.5.0        |
| tty-spinner                            | 0.8.0        |
| word_wrap                              | 1.0.0        |
| nanaimo                                | 0.2.4        |
| xcodeproj                              | 1.5.7        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.2.8        |
| xcpretty-travis-formatter              | 1.0.0        |
| fastlane-plugin-increment_version_code | 0.4.3        |
</details>

*generated on:* **2018-04-03**
</details>
```

**Comment by JesseScott** [comment]
To be more clear on what is happening above, I have a lane that iterates through all the Google Play tracks (internal, alpha, beta, production), finds the largest versionCode, converts it to an Int, and increments it. This value is then passed on to your lane, where it is throwing a Type exception.

**Comment by JesseScott** [comment]
Disregard - this was my error - i had a type conversion issue that wasn't surfaces properly in my own lane...
